### ISSUE TITLE
Failing to retrieve secret with some combination of 3 out of 5

### ISSUE THREAD

**Issue by assafshomer** [grempe/secretsharing#3] opened 2014-02-06 09:28 UTC
# This combination fails

```
[27] pry(main)> secret='100057108055106048110037051094112064114038050069035073097053043122033082121074107056090102067'
=> "100057108055106048110037051094112064114038050069035073097053043122033082121074107056090102067"
[28] pry(main)> s=SecretSharing::Shamir.new(5,3)
=> #<SecretSharing::Shamir:0x0000000771f820
 @k=3,
 @n=5,
 @received_shares=[],
 @secret=nil,
 @shares=[]>
[29] pry(main)> s.set_fixed_secret(secret)
=> #<OpenSSL::BN:0x0000000784c810>
[30] pry(main)> shares=s.shares.map(&:to_s)
=> ["001FF69184824D423CC4BA75B320143BB541358BC03C0DF81BC899DF25F267E3B334304E7DD81807DB5A4D",
 "00279F04A8FE67F4331423AE9B867529800816314A1B77ED518F1390073495648F2FE98411547D3E6B8A4D",
 "003A0B40BA0C9D4FCD6AF67D7D8827460B297031517EC08C011997F1EAA843EFF9CA0A88CA92EB6DAB614D",
 "004173B45B7ACED550BC932E259252A9156A5438BD665E7D42A682704D04D7385F302935CA9936294607E4D",
 "005F2F13A1DF5803EE2ED8DD2E5D7F0B627B9040D8D0EDC5CD7AC0C8B82424267AD983FFAE55E01E06BF4D"]
[31] pry(main)> r=SecretSharing::Shamir.new(3)
=> #<SecretSharing::Shamir:0x000000078f4880
 @k=3,
 @n=3,
 @received_shares=[],
 @secret=nil,
 @shares=[]>
[32] pry(main)> r<<shares[0]
=> false
[33] pry(main)> r<<shares[1]
=> false
[34] pry(main)> r<<shares[4]
OpenSSL::BNError: no inverse
from /home/assaf/.rvm/gems/ruby-2.0.0-p353/gems/secretsharing-0.3/lib/secretsharing/shamir.rb:225:in `mod_inverse'
[35] pry(main)> 
```
# This combination succeeds

```
[36] pry(main)> r2=SecretSharing::Shamir.new(3)
=> #<SecretSharing::Shamir:0x00000006119dc8
 @k=3,
 @n=3,
 @received_shares=[],
 @secret=nil,
 @shares=[]>
[37] pry(main)> r2<<shares[2]
=> false
[38] pry(main)> r2<<shares[1]
=> false
[39] pry(main)> r2<<shares[0]
=> true
[40] pry(main)> r2.secret.to_s
=> "100057108055106048110037051094112064114038050069035073097053043122033082121074107056090102067"
[41] pry(main)> 
```

**Comment by assafshomer** [comment] 2014-02-06 10:29
## A more general way to test is:

```
shares.combination(3).each do |combo|
  p "trying combination #{combo.map {|x| shares.index(x)}}"  
  r=SecretSharing::Shamir.new(3)
    combo.each do |share|
      p "Adding share: #{share}"
      r << share
      p "Currently secret is #{r.secret.to_s}"
    end  
end 
```

It always fails on the second combination:

```
"trying combination [0, 1, 2]"
"Adding share: 001FCE53E3F39D912E5E9674AABD59AE02581CEF650FD41047DC616D15F43ABE8F0EE61D5C57259E4D814D"
"Currently secret is "
"Adding share: 002B679C706D854F8E7139240CCA2C8AF22903D36030C8FB5D1C10B9D49A10A710545267268110583A224D"
"Currently secret is "
"Adding share: 00315DDC0F20604750AB4A2E0EA7B7D137A4782ECA543616D9F8538C582D33D26E9A723C56E9B7BF6A4634D"
"Currently secret is 100057108055106048110037051094112064114038050069035073097053043122033082121074107056090102067"
"trying combination [0, 1, 3]"
"Adding share: 001FCE53E3F39D912E5E9674AABD59AE02581CEF650FD41047DC616D15F43ABE8F0EE61D5C57259E4D814D"
"Currently secret is "
"Adding share: 002B679C706D854F8E7139240CCA2C8AF22903D36030C8FB5D1C10B9D49A10A710545267268110583A224D"
"Currently secret is "
"Adding share: 004F30C168BD1B01A328D3AB43D14B479AB39A3B34479D670F17D990209FC03E1B075A3834A665E33D394D"
OpenSSL::BNError: no inverse
from /home/assaf/.rvm/gems/ruby-2.0.0-p353/gems/secretsharing-0.3/lib/secretsharing/shamir.rb:226:in `mod_inverse'
[30] pry(main)> 

```

**Comment by grempe** [comment] 2014-02-17 22:04
Thanks for the report.  Life (new baby girl) is keeping me pretty busy right now but I will try to look into your issue and see if I can come up with a fix.  Of course a patch with tests is always appreciated if you've dug into the issue at all.

**Comment by assafshomer** [comment] 2014-02-18 07:23
Hi Glenn.
Thanks for getting back to me.
Congratulations on your new baby girl! Exciting. I have two kids (oldest is
almost 13 and youngest almost 8) but I still remember the early days, so
good luck. Life is definitely more important than Shamir Secret Sharing (or
any computer program for that matter).
I am interested in sending a patch myself, however, right now I'm too busy
to spend the time needed in order to dig deeper into your code so I'll try
to do that in a few weeks time when my schedule looks a littler saner.

Thanks anyways for sharing your work!

-- Assaf.

On Tue, Feb 18, 2014 at 12:04 AM, Glenn Rempe notifications@github.comwrote:

> Thanks for the report. Life (new baby girl) is keeping me pretty busy
> right now but I will try to look into your issue and see if I can come up
> with a fix. Of course a patch with tests is always appreciated if you've
> dug into the issue at all.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/grempe/secretsharing/issues/3#issuecomment-35327093
> .

## 

Assaf

**Comment by ntalbott** [comment] 2015-01-05 18:30
We've just encountered this issue on a "2 of 4" secret. Any idea on the probable cause?

**Comment by ntalbott** [comment] 2015-01-12 20:25
So I whipped up a little script to help me track this down: https://gist.github.com/ntalbott/2c7fe4d48b2295463a65

#5 is the result - basically, I think prime number generation is flat broken for various bit lengths. Simply swapping in OpenSSL standard prime generation fixes it for all cases I could find.

**Comment by grempe** [comment] 2015-01-13 04:00
Hello all.  Thanks for your commitment to tracking down this issue.  I just have not had time to look into this as of late.  I just pushed some commits that I had done in before the new year and I ended up doing much the same as @ntalbott, but for reasons of simplicity, and not really trusting the previous prime generation code.  I didn't know it was a possible source of this issue.  Please take a look at 5e9fe0489aae807742268738351d460b8b33cfc0 and please give me a new pull request with any tests you think will help make sure the problem is gone and stays that way and I'll merge it right away. When I get your tests and any other changes merged in, I'll close this issue if it looks good.

Please exercise this new version and let me know if you can break it. @ntalbott I ran your gist script a whole bunch of times on this newer version of the code and I received no aborts.

Ultimately I'd like to eliminate the dependency on OpenSSL altogether for this gem, and I have some WIP code to achieve that.  We'll see if I can get there.

Also, if you don't mind.  I am curious as to what purpose you are all using the gem now?  If you feel you can share some info about your project I'd love to hear it (or privately in email if you like).

**Comment by grempe** [comment] 2015-01-13 04:09
Never mind on the pull request @ntalbott.  I just grabbed your extra test and committed it myself.  Thanks!

I'll close this issue now as resolved.  If you see it come back please let me know and we can re-open.

Thanks.

**Closed as completed by grempe** 2015-01-13 04:09 UTC

**Comment by ntalbott** [comment] 2015-01-13 16:42
Thanks so much for getting this all merged @grempe!

**Comment by ntalbott** [comment] 2015-01-13 16:46
Background on my use of the library: we're using it as part of a key management system at @spreedly. It's much more convenient for us than shelling out to `ssss`, and being able to easily hack on it is a plus too.

**Comment by grempe** [comment] 2015-01-13 20:23
FYI, version 1.0.0 of the gem has been released to rubygems. Please let me know if you see any issues.

https://rubygems.org/gems/secretsharing

:-)

**Comment by ntalbott** [comment] 2015-01-13 20:30
:cool: :heart:
